package pizzaPricePackage;
import javax.swing.JOptionPane;

/**
 *
 * Daniel Ghita
 * February 15 2022
 */
public class pizzaPrice extends javax.swing.JFrame {
    double costToppings = 0, cost, diameter;
    boolean extraCheese, pepperoni, bacon, ham, mushrooms, peppers;
    public pizzaPrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCost = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chkPepperoni = new javax.swing.JCheckBox();
        chkExtraCheese = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkHam = new javax.swing.JCheckBox();
        chkMushrooms = new javax.swing.JCheckBox();
        chkPeppers = new javax.swing.JCheckBox();
        spinInches = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Diameter of pizza (Inches):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnCalculate.setText("Calculate Price");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 322, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pizza Price Calculator");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtCost.setColumns(20);
        txtCost.setRows(5);
        jScrollPane1.setViewportView(txtCost);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 100));

        jLabel3.setText("Price:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Toppings:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, -1, -1));

        chkPepperoni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkPepperoni.setText("Pepperoni");
        chkPepperoni.setAlignmentY(0.0F);
        getContentPane().add(chkPepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 20));

        chkExtraCheese.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkExtraCheese.setText("Extra Cheese");
        chkExtraCheese.setAlignmentY(0.0F);
        chkExtraCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExtraCheeseActionPerformed(evt);
            }
        });
        getContentPane().add(chkExtraCheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        chkBacon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkBacon.setText("Bacon");
        getContentPane().add(chkBacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        chkHam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkHam.setText("Ham");
        getContentPane().add(chkHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        chkMushrooms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkMushrooms.setText("Mushrooms");
        getContentPane().add(chkMushrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        chkPeppers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkPeppers.setText("Peppers");
        getContentPane().add(chkPeppers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        spinInches.setModel(new javax.swing.SpinnerNumberModel(12, 6, 24, 2));
        getContentPane().add(spinInches, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("$1 Per Topping");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 305, -1, -1));

        setBounds(0, 0, 305, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
            diameter = (int) spinInches.getValue();
            
            if (chkExtraCheese.isSelected() == true) {
                costToppings++;
            }
            if (chkPepperoni.isSelected() == true) {
                costToppings++;
            }
            if (chkBacon.isSelected() == true) {
                costToppings++;
            }
            if (chkHam.isSelected() == true) {
                costToppings++;
            }
            if (chkMushrooms.isSelected() == true) {
                costToppings++;
            }
            if (chkPeppers.isSelected() == true) {
                costToppings++;
            }
            System.out.println(costToppings);
            cost = cost + costToppings + 4.00 + 2.50 + (0.50 * diameter);
            String rounded = String.format("%.2f",cost);
            txtCost.setText("$" + rounded);
            costToppings = 0;
            cost = 0;
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void chkExtraCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExtraCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkExtraCheeseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzaPrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkExtraCheese;
    private javax.swing.JCheckBox chkHam;
    private javax.swing.JCheckBox chkMushrooms;
    private javax.swing.JCheckBox chkPepperoni;
    private javax.swing.JCheckBox chkPeppers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinInches;
    private javax.swing.JTextArea txtCost;
    // End of variables declaration//GEN-END:variables
}
