
package coinsPackage;
import javax.swing.JOptionPane;


/**
 * Daniel Ghita
 * February 12 2022
 */
public class coins extends javax.swing.JFrame {

    /**
     * Creates new form coins
     */
    public coins() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();
        txtAmountPaid = new javax.swing.JTextField();
        btnCalculateChange = new javax.swing.JButton();
        txtChangeDue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCoinList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Total Cost:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 40, -1, -1));

        jLabel2.setText("Amount Paid:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 75, -1, 31));

        jLabel3.setText("Change Due:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 172, -1, 21));
        getContentPane().add(txtTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 38, 70, -1));
        getContentPane().add(txtAmountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 81, 70, -1));

        btnCalculateChange.setText("Submit");
        btnCalculateChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculateChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 124, 79, -1));
        getContentPane().add(txtChangeDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 173, 70, -1));

        txtCoinList.setColumns(20);
        txtCoinList.setRows(5);
        jScrollPane1.setViewportView(txtCoinList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 227, -1, 141));

        setBounds(0, 0, 346, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateChangeActionPerformed
 double totalCost, amountPaid, changeDue;
 int change=0;
 try {
 totalCost=Double.parseDouble(txtTotalCost.getText());
 amountPaid=Double.parseDouble(txtAmountPaid.getText());
 
     changeDue = amountPaid - totalCost;

     if (changeDue < 0) {
         JOptionPane.showMessageDialog(coins.this, "ERROR:\nPayment Amount Entered Is Insuffiecient to Complete Transaction!");
     } else {
         txtChangeDue.setText(String.format("%.2f", changeDue));
         change = (int) Math.round(changeDue * 100);
         String s = "";
         while (change >= 200) {
             s += " $2.00 Toonie \n";
             change -= 200;
         }
         if (change >= 100) {
             s += " $1.00 Loonie \n";
             change -= 100;
         }
         while (change >= 25) {
             s += " $0.25 Quarter \n";
             change -= 25;
         }
         if (change >= 10) {
             s += " $0.10 Dime \n";
             change -= 10;
         }
         if (change >= 5) {
             s += " $0.05 Nickel \n";
             change -= 5;
         }

         txtCoinList.setText(s);
     }
 }
 catch(NumberFormatException e) {
 JOptionPane.showMessageDialog(coins.this, "ERROR:\nPlease Insert Correctly Formatted Number!");
 }

    }//GEN-LAST:event_btnCalculateChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAmountPaid;
    private javax.swing.JTextField txtChangeDue;
    private javax.swing.JTextArea txtCoinList;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
