/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatePackage;
import javax.swing.JOptionPane;

/**
 * Daniel Ghita
 * February 14 2022
 */
public class calculate extends javax.swing.JFrame {

    double A, B, answer;

    public calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtAdd = new javax.swing.JTextField();
        btnSubtract = new javax.swing.JButton();
        txtSubtract = new javax.swing.JTextField();
        btnMultiply = new javax.swing.JButton();
        txtMultiply = new javax.swing.JTextField();
        btnDivide = new javax.swing.JButton();
        txtDivide = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, -1));

        jButton1.setText("A + B =");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        getContentPane().add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, -1));

        btnSubtract.setText("A - B =");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, -1));
        getContentPane().add(txtSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, -1));

        btnMultiply.setText("A * B =");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, -1));
        getContentPane().add(txtMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, -1));

        btnDivide.setText("A / B =");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));
        getContentPane().add(txtDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 60, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        setBounds(0, 0, 271, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        A = Double.parseDouble(txtA.getText());
        B = Double.parseDouble(txtB.getText());
        answer = A +B;
        txtAdd.setText(Double.toString(answer));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        try {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A - B;
            txtSubtract.setText(String.format("%.2f",answer));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        try {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A * B;
            txtMultiply.setText(String.format("%.2f", answer));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        try {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A / B;
            txtDivide.setText(String.format("%.2f", answer));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtA.setText("");
        txtB.setText("");
        txtAdd.setText("");
        txtSubtract.setText("");
        txtMultiply.setText("");
        txtDivide.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtDivide;
    private javax.swing.JTextField txtMultiply;
    private javax.swing.JTextField txtSubtract;
    // End of variables declaration//GEN-END:variables
}
