/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablePackage;
import javax.swing.JOptionPane;

/**
 * Daniel Ghita
 * February 11 2022
 */
public class timetable extends javax.swing.JFrame {

int[] journey=new int[6];
 int starthours, startminutes;
 
    public timetable() {
        initComponents();
        tblTrainTimes.getModel().setValueAt("Machynlleth", 0, 0);
        tblTrainTimes.getModel().setValueAt("Tywyn", 1, 0);
        tblTrainTimes.getModel().setValueAt("Barmouth", 2, 0);
        tblTrainTimes.getModel().setValueAt("Harlech", 3, 0);
        tblTrainTimes.getModel().setValueAt("Porthmadog", 4, 0);
        tblTrainTimes.getModel().setValueAt("Pwllheli", 5, 0);

        journey[1] = 26;
        journey[2] = 27;
        journey[3] = 22;
        journey[4] = 19;
        journey[5] = 24;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        txtMinutes = new javax.swing.JTextField();
        btnTimetable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainTimes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablePackage/resources/ROUTES.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setText("Hours:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 47, -1, -1));

        jLabel3.setText("Minutes:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 47, -1, -1));

        txtHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursActionPerformed(evt);
            }
        });
        getContentPane().add(txtHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 45, 65, -1));
        getContentPane().add(txtMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 45, 65, -1));

        btnTimetable.setText("Show Timetable");
        btnTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimetableActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 82, -1, -1));

        tblTrainTimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Hours", "Minutes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTrainTimes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 166, 343, 128));

        jLabel4.setText("Departure time from Machynlleth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 12, -1, -1));

        setBounds(0, 0, 758, 408);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursActionPerformed

    private void btnTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimetableActionPerformed
        String s;
        int hours, minutes;
        try {
            if (txtMinutes.getText().equals("")) {
                startminutes = 0;
            } else {
                s = txtMinutes.getText();
                startminutes = Integer.parseInt(s);
            }

            if (txtHours.getText().equals("")) {
                starthours = 0;
            } else {
                s = txtHours.getText();
                starthours = Integer.parseInt(s);
            }
            hours = starthours;
            minutes = startminutes;
            if (hours >= 0 && hours <= 23) {
                if (minutes >= 0 && minutes <= 59) {
                    tblTrainTimes.getModel().setValueAt(hours, 0, 1);
                    tblTrainTimes.getModel().setValueAt(minutes, 0, 2);
                    for (int i = 1; i <= 5; i++) {
                        minutes += journey[i];
                        if (minutes > 59) {
                            minutes -= 60;
                            hours++;
                        }
                        if (hours > 23) {
                            hours = 0;
                        }
                        tblTrainTimes.getModel().setValueAt(hours, i, 1);
                        tblTrainTimes.getModel().setValueAt(minutes, i, 2);
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(timetable.this, "ERROR:\nPlease Enter Valid Number Value");
        }
    }//GEN-LAST:event_btnTimetableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrainTimes;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtMinutes;
    // End of variables declaration//GEN-END:variables
}
